### ISSUE TITLE
Could not determine the dependencies of task ':app:lintVitalRelease'.

### ISSUE THREAD

**Issue by yasamanjanfeshani** [adtrace/adtrace_sdk_react_native#14]
when adding adtarce into my project in development everything is ok but when I try to use ./gradlew assembleRelease I got an error. I don't know what's wrong.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download bolts-tasks-1.4.0.jar (com.parse.bolts:bolts-tasks:1.4.0)
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/parse/bolts/bolts-tasks/1.4.0/bolts-tasks-1.4.0.jar'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/parse/bolts/bolts-tasks/1.4.0/bolts-tasks-1.4.0.jar'.
            > repo.maven.apache.org:443 failed to respond

OS: windows

my build.gradle is this:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        googlePlayServicesVersion = "+"
        firebaseMessagingVersion = "21.1.0"
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlin_version = '1.3.50' 
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.2')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'
        classpath 'com.google.firebase:perf-plugin:1.4.0'  // Performance Monitoring plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        google()
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }

        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

![WhatsApp Image 2022-01-30 at 10 49 21 PM](https://user-images.githubusercontent.com/48978016/151748897-b824a9b8-995f-4128-a1f9-a60b7fb46154.jpeg)
![WhatsApp Image 2022-01-30 at 10 49 29 PM](https://user-images.githubusercontent.com/48978016/151748907-5e642733-6fc1-4288-a72b-a56dfe3e3a4e.jpeg)

**Comment by namini40** [comment]
@ya30janfeshani our new version is released. you may want to take a look! [V2.0.3](https://github.com/adtrace/adtrace_sdk_react_native/releases/tag/v2.0.3)
