### ISSUE TITLE
setAttributionCallbackListener

### ISSUE THREAD

**Issue by amereii** [adtrace/adtrace_sdk_react_native#5]
سلام

@arefhosseini 

تابع
setAttributionCallbackListener
چرا صدا زده نمیشه؟

https://github.com/adtrace/adtrace_sdk_react_native#attribution-callback

**Comment by namini40** [comment]
@amereii @ya30janfeshani our new version is released. you may want to take a look! [V2.0.3](https://github.com/adtrace/adtrace_sdk_react_native/releases/tag/v2.0.3)
